light.ute_terrasse_light:
  icon: mdi:coach-lamp

sensor.ute_number_of_lights_on:
  icon: mdi:lightbulb-on-outline

cover.ute_garage_door:
  icon: mdi:garage-open

light.ute_garasje_light:
  icon: mdi:ceiling-light