sensor.inne_etg1_inngangsdoor:
  icon: mdi:door-closed

sensor.inne_etg1_number_of_lights_on:
  icon: mdi:lightbulb-on-outline

switch.inne_etg1_gang_light:
  icon: mdi:ceiling-light

sensor.inne_etg1_gang_gulvvarme:
  icon: mdi:radiator

switch.inne_etg1_garderobe_light:
  icon: mdi:ceiling-light

sensor.inne_etg1_garderobe_bevegelse:
  icon: mdi:motion-sensor

switch.inne_etg1_stue_spisestue_light:
  icon: mdi:ceiling-light

switch.inne_etg1_stue_sofa_light:
  icon: mdi:floor-lamp

sensor.inne_etg1_stue_gulvvarme:
  icon: mdi:radiator

sensor.inne_etg1_stue_rullgardiner:
  icon: mdi:blinds-open

switch.scene_etg1_stua_dag:
  icon: mdi:home

switch.scene_etg1_stua_kveld:
  icon: mdi:weather-night

switch.scene_etg1_stua_selskap:
  icon: mdi:glass-wine

switch.scene_etg1_stua_alt_av:
  icon: mdi:power

switch.inne_etg1_kjokken_light:
  icon: mdi:ceiling-light

sensor.inne_etg1_kjokken_gulvvarme:
  icon: mdi:radiator

switch.inne_etg1_tv_light:
  icon: mdi:ceiling-light

sensor.inne_etg1_tv_gulvvarme:
  icon: mdi:radiator

sensor.inne_etg1_tv_rullgardiner:
  icon: mdi:blinds

switch.scene_etg1_tv_dag:
  icon: mdi:home

switch.scene_etg1_tv_kveld:
  icon: mdi:weather-night

switch.scene_etg1_tv_film:
  icon: mdi:popcorn

switch.scene_etg1_tv_alt_av:
  icon: mdi:power

switch.inne_etg1_bad_light:
  icon: mdi:ceiling-light

sensor.inne_etg1_bad_gulvvarme:
  icon: mdi:radiator