inne_etg0_vaskerom_light:
  friendly_name: 'Lys'
  value_template: 'off'
  turn_on:
  turn_off:

inne_etg0_gang_light:
  friendly_name: 'Lys'
  value_template: 'off'
  turn_on:
  turn_off:

inne_etg0_soverom1_light:
  friendly_name: 'Lys'
  value_template: 'off'
  turn_on:
  turn_off:

inne_etg0_soverom2_light:
  friendly_name: 'Lys'
  value_template: 'off'
  turn_on:
  turn_off:

inne_etg0_bad_light:
  friendly_name: 'Lys'
  value_template: 'off'
  turn_on:
  turn_off:

inne_etg0_tekniskrom_light:
  friendly_name: 'Lys'
  value_template: 'off'
  turn_on:
  turn_off:

inne_etg0_treningsrom_light:
  friendly_name: 'Lys'
  value_template: 'off'
  turn_on:
  turn_off: