homeassistant:
  # Customization file
  customize: !include_dir_merge_named customize/

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes/

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

sun:

weather:
  - platform: met

light: !include_dir_merge_list light/
lock: !include_dir_merge_list lock/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/