inne_etg0_average_temperature:
  friendly_name: 'Gjennomsnittstemperatur'
  value_template: '{{ ((float(23.1) + float(20.05) + float(14.20) + float(14.05) + float(12.79)) / 5) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_number_of_lights_on:
  friendly_name: 'Antall rom med lys på'
  value_template: >-
    {% set total = 0 %}
    {{total}}

inne_etg0_vaskerom_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(23.1))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_vaskerom_vaskemaskin:
  friendly_name: 'Vaskemaskin'
  value_template: 'on'

inne_etg0_vaskerom_torketrommel:
  friendly_name: 'Tørketrommel'
  value_template: 'off'

inne_etg0_vaskerom_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'on'

inne_etg0_gang_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'on'

inne_etg0_soverom1_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'off'

inne_etg0_soverom2_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'off'

inne_etg0_bad_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'off'

inne_etg0_gang_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(20.05))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_soverom1_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(14.20))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_soverom2_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(14.05))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_bad_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(12.79))/ 1) | round(2) }}'
  unit_of_measurement: °C