ute_average_temperature:
  friendly_name: 'Gjennomsnittstemperatur i rom'
  value_template: '{{ ((float(4.6))/ 1) | round(2) }}'
  unit_of_measurement: 째C

ute_number_of_lights_on:
  friendly_name: 'Antall omr책der med lys p책'
  value_template: >-
    {% set total = 0 %}
    {% if is_state('switch.ute_terrasse_light', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {% if is_state('switch.ute_garasje_light', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {{total}}

ute_terrasse_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(4.6))/ 1) | round(2) }}'
  unit_of_measurement: 째C