inne_average_etg2_temperature:
  friendly_name: 'Gjennomsnittstemperatur'
  value_template: '{{ ((float(21.4))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg2_number_of_lights_on:
  friendly_name: 'Antall rom med lys på'
  value_template: >-
    {% set total = 2 %}
    {{total}}