# Gjennomsnittstemperatur
ute_average_temperature:
  friendly_name: 'Gjennomsnittstemperatur i rom'
  value_template: '{{ ((float(4.6))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_average_temperature:
  friendly_name: 'Gjennomsnittstemperatur'
  value_template: '{{ ((float(17.3) + float(20.6) + float(21.4)) / 3) | round(2) }}'
  unit_of_measurement: °C

# Lysstatus
ute_number_of_lights_on:
  friendly_name: 'Antall områder med lys på'
  value_template: >-
    {% set total = 0 %}
    {% if is_state('sensor.ute_terrasse_light', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {% if is_state('sensor.ute_garasje_light', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {{total}}

inne_number_of_lights_on:
  friendly_name: 'Antall rom med lys på'
  value_template: >-
    {% set total = 6 %}
    {{total}}

#DEMO
ute_terrasse_light:
  friendly_name: 'Lys'
  value_template: 'on'

ute_terrasse_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(4.6))/ 1) | round(2) }}'
  unit_of_measurement: °C

ute_garasje_light:
  friendly_name: 'Lys'
  value_template: 'on'

ute_garasjedoor:
  friendly_name: 'Garasjedør'
  value_template: 'Åpen'

inne_inngangsdoor:
  friendly_name: 'Inngangsdør'
  value_template: 'Åpen'

inne_vaskeromsdoor:
  friendly_name: 'Vaskeromsdør'
  value_template: 'Låst'

inne_average_etg0_temperature:
  friendly_name: 'Gjennomsnittstemperatur'
  value_template: '{{ ((float(23.1) + float(20.05) + float(14.20) + float(14.05) + float(12.79)) / 5) | round(2) }}'
  unit_of_measurement: °C

inne_average_etg1_temperature:
  friendly_name: 'Gjennomsnittstemperatur'
  value_template: '{{ ((float(20.6))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_average_etg2_temperature:
  friendly_name: 'Gjennomsnittstemperatur'
  value_template: '{{ ((float(21.4))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_number_of_lights_on:
  friendly_name: 'Antall rom med lys på'
  value_template: >-
    {% set total = 0 %}
    {{total}}

inne_etg1_number_of_lights_on:
  friendly_name: 'Antall rom med lys på'
  value_template: >-
    {% set total = 4 %}
    {{total}}

inne_etg2_number_of_lights_on:
  friendly_name: 'Antall rom med lys på'
  value_template: >-
    {% set total = 2 %}
    {{total}}

inne_etg0_vaskerom_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(23.1))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_vaskerom_light:
  friendly_name: 'Lys'
  value_template: 'off'

inne_etg0_vaskerom_vaskemaskin:
  friendly_name: 'Vaskemaskin'
  value_template: 'on'

inne_etg0_vaskerom_torketrommel:
  friendly_name: 'Tørketrommel'
  value_template: 'off'

inne_etg0_vaskerom_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'on'

inne_etg0_gang_light:
  friendly_name: 'Lys'
  value_template: 'off'

inne_etg0_gang_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'on'

inne_etg0_soversom1_light:
  friendly_name: 'Lys'
  value_template: 'off'

inne_etg0_soverom1_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'off'

inne_etg0_soverom2_light:
  friendly_name: 'Lys'
  value_template: 'off'

inne_etg0_soverom2_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'off'

inne_etg0_bad_light:
  friendly_name: 'Lys'
  value_template: 'off'

inne_etg0_bad_gulvvarme:
  friendly_name: 'Gulvvarme'
  value_template: 'off'

inne_etg0_tekniskrom_light:
  friendly_name: 'Lys'
  value_template: 'off'

inne_etg0_tekniskrom_stromforbruk:
  friendly_name: 'Husets strømforbruk'
  value_template: '509w'

inne_etg0_treningsrom_light:
  friendly_name: 'Lys'
  value_template: 'off'

inne_etg0_gang_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(20.05))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_soverom1_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(14.20))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_soverom2_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(14.05))/ 1) | round(2) }}'
  unit_of_measurement: °C

inne_etg0_bad_temperature:
  friendly_name: 'Temperatur'
  value_template: '{{ ((float(12.79))/ 1) | round(2) }}'
  unit_of_measurement: °C