utebod_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.utebod_motion_sensor', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}

gangen_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.gangen_motion_sensor', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}

boden_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.boden_motion_sensor', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}

soverommet_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.soverommet_motion_sensor', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}